apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
data:
  defaults.ini: |
    app_mode = production

    instance_name = ${HOSTNAME}

    [paths]
    data = /grafana/data
    logs = /grafana/logs
    plugins = /grafana/plugins

    [server]
    protocol = http
    http_addr =
    http_port = 3000
    domain = localhost
    enforce_domain = false
    root_url = %(protocol)s://%(domain)s:%(http_port)s/

    # Log web requests
    router_logging = false

    # the path relative working path
    static_root_path = public

    # enable gzip
    enable_gzip = true

    # https certs & key file
    cert_file =
    cert_key =

    [database]
    {{- if .Values.mariadb.enabled }}
    type = mysql
    host = {{ .Values.mariadb.host }}:3306
    name = {{ template "mariadb.name" . }}
    user = root
    password =
    {{- else }}
    type = sqlite3
    {{- end }}

    ssl_mode = disable

    ca_cert_path =
    client_key_path =
    client_cert_path =
    server_cert_name =

    path = grafana.db

    [session]
    provider = file
    provider_config = sessions
    cookie_name = grafana_sess
    cookie_secure = false
    session_life_time = 86400
    gc_interval_time = 86400

    [analytics]
    reporting_enabled = false
    check_for_updates = true

    google_analytics_ua_id =
    google_tag_manager_id =

    [security]
    {{- if .Values.admin.set }}
    admin_user = admin
    admin_password = {{ template "grafana.init.password" . }}
    {{- else }}
    admin_user = admin
    admin_password = admin
    {{- end }}

    secret_key = SW2YcwTIb9zpOOhoPsMm
    login_remember_days = 7
    cookie_username = grafana_user
    cookie_remember_name = grafana_remember
    disable_gravatar = false
    data_source_proxy_whitelist =

    [snapshots]
    external_enabled = true
    external_snapshot_url = https://snapshots-origin.raintank.io
    external_snapshot_name = Publish to snapshot.raintank.io

    [users]
    allow_sign_up = false
    allow_org_create = false
    auto_assign_org = false
    auto_assign_org_role = Viewer
    verify_email_enabled = false
    login_hint = email or username
    default_theme = dark

    [auth.anonymous]
    enabled = false
    org_name = Main Org.
    org_role = Viewer

    [smtp]
    enabled = false
    host = localhost:25
    user =
    password =
    cert_file =
    key_file =
    skip_verify = false
    from_address = admin@grafana.localhost

    [emails]
    welcome_email_on_sign_up = false
    templates_pattern = emails/*.html

    [log]
    mode = console, file
    level = info

    [log.console]
    level =
    format = console

    [log.file]
    level =
    format = text
    log_rotate = true
    max_lines = 1000000
    max_size_shift = 28
    daily_rotate = true
    max_days = 7

    [log.syslog]
    level =
    format = text
    network =
    address =
    facility =
    tag =

    [dashboards.json]
    enabled = false
    path = /grafana/dashboards

    [metrics]
    enabled           = true
    interval_seconds  = 60

    # Send internal Grafana metrics to graphite
    ; [metrics.graphite]
    ; address = localhost:2003
    ; prefix = prod.grafana.%(instance_name)s.

    [grafana_net]
    url = https://grafana.net
