apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  #annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
  #  "helm.sh/hook": post-install
spec:
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
      - name: {{ template "fullname" . }}
        image: asia.gcr.io/orange-sys/alpine-job:0.1.4
        env:
        - name: READ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "influxdb.fullname" . }}
              key: read-password
        command: ["/bin/sh", "-c"]
        args:
          # FIXME use kubernetes probe instead of "until curl"
          - >
            until $(http -a admin:admin --check-status --ignore-stdin http://{{ template "fullname" . }}:3000/api/datasources &> /dev/null); do
              printf '.'; sleep 1;
            done ;
            http --ignore-stdin POST http://admin:admin@{{ template "fullname" . }}:3000/api/datasources \
              name=influxdb \
              type=influxdb \
              url=http://{{ template "influxdb.fullname" . }}:8086 \
              access=proxy \
              database=telegraf \
              user=_read \
              password=${READ_PASSWORD}
