{{- if .Values.production.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  #annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
  #  "helm.sh/hook": post-install
spec:
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
      - name: {{ template "fullname" . }}
        image: orangesys/alpine-job:0.1.7
        env:
        - name: READ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "influxdb.fullname" . }}
              key: read-password
        command: ["/bin/sh", "-c"]
        args:
          # FIXME use kubernetes probe instead of "until curl"
          - >
            until $(http -a admin:{{- if .Values.admin.set }}{{ template "grafana.init.password" . }}{{- else }}admin{{- end }} --check-status --ignore-stdin http://{{ template "fullname" . }}/api/datasources &> /dev/null); do
              printf '.'; sleep 1;
            done ;
            http --ignore-stdin POST http://admin:{{- if .Values.admin.set }}{{ template "grafana.init.password" . }}{{- else }}admin{{- end }}@{{ template "fullname" . }}/api/datasources \
              name=influxdb \
              type=influxdb \
              url=http://{{ template "influxdb.fullname" . }} \
              access=proxy \
              database=telegraf \
              user=_read \
              password=${READ_PASSWORD}

{{- end }}
