version: 2

jobs:
  build:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
    steps:
      - checkout
      - run:
          name: Install kubectl cli
          command: |
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl 
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
      - run:
          name: Install minikube
          command: |
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 
            chmod +x minikube
            sudo mv minikube /usr/local/bin/
      - run:
          name: Init minikube
          command: |
            sudo minikube start --vm-driver=none --kubernetes-version=v1.7.0
            sudo minikube update-context
            JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until sudo kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
      - run:
          name: Check minikube
          command: |
            sudo kubectl cluster-info
      - run:
          name: Install helm to minikube
          command: |
            wget https://storage.googleapis.com/kubernetes-helm/helm-v2.6.1-linux-amd64.tar.gz
            tar -zxf helm-v2.6.1-linux-amd64.tar.gz
            sudo linux-amd64/helm init
      - run:
          command: |
            sudo kubectl get pods --all-namespaces