version: 2

jobs:
  build:
    docker:
      - image: golang:1.8.3
    working_directory: ~/charts
    steps:
      - checkout
      - run:
          name: install helm client
          command: |
            set +o pipefail
            curl -sSL http://storage.googleapis.com/kubernetes-helm/helm-v2.1.3-linux-amd64.tar.gz|tar -xz 
            mv linux-amd64/helm /usr/sbin
            chmod +x /usr/sbin/helm
      - run:
          name: create package and index
          command: |
            set +o pipefail
            ./scripts/helm-package.sh
            ./scripts/create-index.sh
      - run:
          name: sync to github
          command: |
            set +o pipefial
            git add docs
            git commit -m "change helm pakacke with circlci"
            git push