# Default values for traefik.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
imageTag: "v1.2.0-alpine"

# resources limits
cpu: 200m
memory: 30Mi

# create a database user
##
# postgresUser:

# create a database
# postgresDatabase:

# Number of postgrest instances to run
replicaCount: 1

persistence:
  enabled: false

dashboard:
  enabled: true
