# Default values for traefik.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
imageTag: "v1.1.0-rc1"

# resources limits
cpu: 200m
memory: 30Mi

# create a database user
##
# postgresUser:

# create a database
# postgresDatabase:

# Number of postgrest instances to run
replicaCount: 1

## Persist data to a persitent volume
persistence:
  enabled: true
  storageClass: generic
  accessMode: ReadWriteOnce
  size: 5Gi
