description: A Helm chart for Kubernetes
name: grafana
version: 0.1.21
description: Chart for grafana
keywords:
  - grafana
  - dashboard
maintainers:
  - name: gavin zhou
    email: gavin.zhou@gmail.com
