apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    version: "{{ .Values.imageTag }}"
spec:
  replicas: {{default 1 .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        version: "{{ .Values.imageTag }}"
      annotations:
        "helm.sh/created": {{ .Release.Time.Seconds | quote }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: {{ template "fullname" . }}
        image: "asia.gcr.io/orange-sys/alpine-influxdb:{{.Values.imageTag}}"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /ping
            port: 8086
            httpHeaders:
              - name: X-Influxdb-Version
                value: {{.Values.imageTag}}
          initialDelaySeconds: 45
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /ping
            port: 8086
            httpHeaders:
              - name: X-Influxdb-Version
                value: {{.Values.imageTag}}
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "{{.Values.cpu}}"
            memory: "{{.Values.memory}}"
          requests:
            cpu: "{{.Values.cpu}}"
            memory: "{{.Values.memory}}"
        ports:
        - containerPort: 8083
          name: admin
        - containerPort: 8086
          name: http
        volumeMounts:
        - name: config-volume
          mountPath: /etc/influxdb
        - name: influxdb-volume
          mountPath: /var/lib/influxdb
      volumes:
      - name: config-volume
        configMap:
          name: {{ template "fullname" . }}
      - name: influxdb-volume
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
