apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}-admin"
  labels:
    app: "{{ template "fullname" . }}-admin"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: LoadBalancer
  ports:
    - port: 8001
      targetPort: 8001
      name: admin
  selector:
    app: {{ template "fullname" . }}
    version: "{{ .Values.imageTag }}"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}-peer"
  labels:
    app: "{{ template "fullname" . }}-peer"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  clusterIP: None
  ports:
    - name: peer-tcp
      protocol: TCP
      port: 7946
    - name: perr-udp
      protocol: UDP
      port: 7946
  selector:
    app: {{ template "fullname" . }}
    version: "{{ .Values.imageTag }}"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}-proxy"
  labels:
    app: "{{ template "fullname" . }}-proxy"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  ports:
    - name: proxy
      port: 80
      targetPort: 8000
  selector:
    app: {{ template "fullname" . }}
    version: "{{ .Values.imageTag }}"
