apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    version: "{{ .Values.imageTag }}"
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        version: "{{ .Values.imageTag }}"
      annotations:
        "helm.sh/created": {{ .Release.Time.Seconds | quote }}
        pod.alpha.kubernetes.io/initialized: "true"
        pod.alpha.kubernetes.io/init-containers: '[
            {
                "name": "remove-lost-found",
                "image": "busybox:1.25.0",
                "command": ["rmdir", "/var/lib/postgresql/data/lost+found"],
                "volumeMounts": [
                    {
                        "name": "postgres-data",
                        "mountPath": "/var/lib/postgresql/data"
                    }
                ]
              }
            ]'
    spec:
      terminationGracePeriodSeconds: 0
      restartPolicy: Always
      containers:
      - name: {{ template "fullname" . }}
        image: "asia.gcr.io/orange-sys/alpine-postgres:{{.Values.imageTag}}"
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_USER
            value: {{ default "kong" .Values.postgresUser | quote }}
          - name: POSTGRES_DB
            value: {{ default "kong" .Values.postgresDatabase | quote }}
        resources:
          limits:
            cpu: "{{.Values.cpu}}"
            memory: "{{.Values.memory}}"
          requests:
            cpu: "{{.Values.cpu}}"
            memory: "{{.Values.memory}}"
        ports:
          - name: postgres
            containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-data
      volumes:
        - name: postgres-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "fullname" . }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
