apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ssl-sysapi-orangesys-io
  namespace: apigateway
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - sysapi.orangesys.io
    secretName: sysapi.orangesys.io
  rules:
  - host: "sysapi.orangesys.io"
    http:
      paths:
      - path: /create
        backend:
          serviceName: sys-orangeapi
          servicePort: 80
      - path: /storageusage
        backend:
          serviceName: sys-orangeapi
          servicePort: 80
      - path: /
        backend:
          serviceName: sys-orangeapi
          servicePort: 80
