# Default values for kong.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
imageTag: "0.9.3"

# resources limits
cpu: 100m
memory: 256Mi

# create a database user
##
# kongDatabase:

# create a database
# kongPGHost:

# Number of instances to run
replicaCount: 1
