# Default values for postgres.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
imageTag: "9.5.4"

# resources limits
cpu: 100m
memory: 200Mi

# create a database user
##
# postgresUser:

# create a database
# postgresDatabase:

# Number of postgrest instances to run
replicaCount: 1

## Persist data to a persitent volume
persistence:
  enabled: true
  storageClass: generic
  accessMode: ReadWriteOnce
  size: 5Gi
