# Default values for influxdb.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
imageTag: "1.0.1"

# resources limits
cpu: 100m
memory: 256Mi

## Specify password for admin user
##
# AdminUser: admin
## Default: random 10 character string
# AdminPassword: testing

## Specify password for read user
##
# ReadUser: _read
## Default: random 10 character string
# ReadPassword: testing

## Specify password for write user
##
# WriteUser: _write
## Default: random 10 character string
# WritePassword: testing

## create a database
##
## Default: telegraf
Database: telegraf

# Number of instances to run
replicaCount: 1

# retention Policy
#retentionPolicy:

## Persist data to a persitent volume
persistence:
  enabled: true
  storageClass: generic
  accessMode: ReadWriteOnce
