apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
      annotations:
        pod.alpha.kubernetes.io/init-containers: '[
              {
                  "name": "batch-jobs-with-git",
                  "image": "asia.gcr.io/saas-orangesys-io/alpine-job:0.1.7",
                  "command": ["git", "clone", "https://github.com/orangesys/batch-jobs.git", "/batch-jobs"],
                  "volumeMounts": [
                      {
                          "name": "batch-jobs",
                          "mountPath": "/batch-jobs"
                      }
                  ]
              }
          ]'
    spec:
      restartPolicy: Never
      containers:
      - name: {{ template "fullname" . }}-kong
        image: asia.gcr.io/saas-orangesys-io/alpine-job:0.1.7
        env:
        - name: kongAdminAPI
          value: {{ default "" .Values.kongAdminAPI }}
        - name: kongKey
          value: {{ default "" .Values.kongKey }}
        - name: kongSecret
          value: {{ default "" .Values.kongSecret }}
        - name: UserName
          value: {{ .Release.Name }}
        - name: WritePassword
          valueFrom:
            secretKeyRef:
              name: {{ template "influxdb.fullname" . }}
              key: write-password
        command: ["/usr/bin/python", "/batch-jobs/adduser.py"]
        volumeMounts:
          - name: batch-jobs
            mountPath: /batch-jobs
            readOnly: true
      volumes:
        - name: batch-jobs
          emptyDir: {}
