apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
      annotations:
        pod.alpha.kubernetes.io/init-containers: '[
              {
                  "name": "batch-jobs-with-git",
                  "image": "asia.gcr.io/orange-sys/alpine-job:0.1.4",
                  "command": ["git", "clone", "https://github.com/orangesys/batch-jobs.git", "/batch-jobs"],
                  "volumeMounts": [
                      {
                          "name": "batch-jobs",
                          "mountPath": "/batch-jobs"
                      }
                  ]
              }
          ]'
    spec:
      restartPolicy: Never
      containers:
      - name: {{ template "fullname" . }}-kong
        image: asia.gcr.io/orange-sys/alpine-job:0.1.4
        env:
        - name: kongAdminAPI
          value: {{ default "" .Values.kongAdminAPI }}
        - name: kongKey
          value: {{ default "" .Values.kongKey }}
        - name: kongSecret
          value: {{ default "" .Values.kongSecret }}
        - name: UserName
          value: {{ .Release.Name }}
        - name: WritePassword
          valueFrom:
            secretKeyRef:
              name: {{ template "influxdb.fullname" . }}
              key: write-password
        command: ["/usr/bin/python", "/batch-jobs/adduser.py"]
        volumeMounts:
          - name: batch-jobs
            mountPath: /batch-jobs
            readOnly: true
      - name: {{ template "fullname" . }}-ing
        image: asia.gcr.io/orange-sys/alpine-job:0.1.4
        env:
        - name: UserName
          value: {{ .Release.Name }}
        command: ["/bin/sh", "-c"]
        args:
          - >
            sed -i "s/ID/$UserName/" /batch-jobs/consumerId.sed;
            kubectl get ing i-orangesys-io-ingress --namespace apigateway \
              -o yaml|sed '/rules/r /batch-jobs/consumerId.sed'| \
              kubectl replace -f -;
            kubectl get configmap orangesys-lb-traefik --namespace kube-system \
              -o yaml|sed "s/sans = \[/&\"$UserName.i.orangesys.io\", /"| \
              kubectl replace -f -;
        volumeMounts:
          - name: batch-jobs
            mountPath: /batch-jobs
      volumes:
        - name: batch-jobs
          emptyDir: {}
